title:            Nick
titlehilight:     Ornstein
tagline:          Human Computer Interaction, Sensory Neuroscience, Civic Technology, Jazz Piano.
description:      Human Computer Interaction, Sensory Neuroscience, Civic Technology, Jazz Piano.
logo:             nicko_thumb.jpg #INSERT MY PICTURE
url: https://nbso13.github.io/nick_ornstein_portfolio

#NOTE: TO RUN LOCALLY: comment out link above and comment out github pages gem in Gemfile


# Owner/author information
owner:
  name:           Nick Ornstein
  bio:            "Somatosensory neuroscience and computational social science at UChicago."
  email:          nickornstein4@gmail.com
  twitter:        OrnsteinNick
  github:         nbso13
  instagram:      nickornstein 
  # For Google Authorship https://plus.google.com/authorship
# Analytics and webmaster tools stuff goes here
# google_analytics: UA-34129661-2 ## DOUBLE CHECK WTF THIS IS
# google_verify: LTwvMh1s7cdUyjaHqQYsBg-I4ZPy0wm_TKUoU0IT5HU#LTwvMh1s7cdUyjaHqQYsBg-I4ZPy0wm_TKUoU0IT5HU
# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: B3B21CDB59D1FC75DFE9B0D0CC329C8C

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Projects
    url: /projects
  - title: Papers
    url: /papers
  - title: Blog
    url: /blog
  - title: Talks
    url: /talks
  - title: Short-CV
    url: /bio

collections:
  papers:
    output: false # do not create html files for each paper in _papers

defaults:
  - scope:
      type: papers
    values:
      layout: paper

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# syntax_highlighter_opts:
#   coderay:
#     line_numbers:
#     line_numbers_start: 1
#     tab_width: 4
#     bold_every: 10
#     css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks -- was /:categories/:title
permalink:   /:title/

# katex:
#   path_to_js: "assets/js/katex.min.js"

#include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

# gems: ['jekyll/minibundle']

maruku:
  use_tex:  true

# for clean vector diagrams
assets:
  assets:
    - "*.svg"
  sources:
    - _svg

# http://www.rubydoc.info/gems/jekyll-minify-html/1.1.0
#env: production

sass:
  sass_dir: assets/sass
  style: compressed

responsive_image:
  cache: true
  template: _includes/responsive-image.html
  output_path_format: images/resized/%{width}/%{basename}
  strip: true
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

